### ISSUE TITLE
Add support for github enterprise

### ISSUE THREAD

**Issue by gunta** [github-linker/chrome-extension#12]
Basically it would need to:
1) Accept a url other than github.com
2) Read the `.npmrc` file next to `package.json` to see which registry its pointing.

**Comment by just-boris** [comment]
Have enterprise github in my company, +1

**Comment by stefanbuck** [comment]
I had a change to take a look on this and I think this will never be possible, sorry. GitHub enterprise is "just" a more stable and by that older version of github.com. The dom structure (on which the extensions relies) is / could be completely different to github.com so it wouldn't work. 

So we can just wait for a "native" implementation of the GitHub Linker. Please visit the [voting issue](https://github.com/github-linker/chrome-extension/issues/9).

Thank you

**Comment by cogell** [comment]
@stefanbuck I'd like to vote and get all my buddies to vote for this but the issue you link to is locked. Link in question: https://github.com/OctoLinker/browser-extension/issues/9

**Comment by stefanbuck** [comment]
Thanks man 👍  I don't know why I locked the thread. Anyway it's unlocked now, but I don't think it will every become "natively" available.

**Comment by stefanbuck** [comment]
btw I'm working on adding GitHub Enterprise support, but would appreciate any help from the community.

 https://github.com/OctoLinker/browser-extension/issues/75

**Comment by cogell** [comment]
Awesome, thanks. I'll check it out
