### ISSUE TITLE
Update options.changelog

### ISSUE THREAD

**Issue by jameswyse** [github-linker/chrome-extension#26]
I just got an update notification that linked to [github-linker/chrome-extension/releases/](https://github.com/github-linker/chrome-extension/releases) instead of [github-linker/core/releases](https://github.com/github-linker/core/releases)!

**Comment by stefanbuck** [comment]
Thank you for the hint. Yesterday I've uploaded the wrong version which includes the upcoming option page and therefore the notification appears with the wrong link. Now I disabled the notification and options page until the next minor release.
