### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by phpnode** [github-linker/chrome-extension#34]
It seems that the extension has stopped working, perhaps github updated their CSS?

**Comment by stefanbuck** [comment]
Jap that's correct see https://github.com/github-linker/core/issues/15. Will fix it soon.

**Comment by tunnckoCore** [comment]
@stefanbuck we should reinstall extension?

**Comment by stefanbuck** [comment]
No, reinstall is not needed. Just keep in mind that the publish process may take up to 60 minutes to appear in the Chrome Web Store. Fix version number is 3.6.0.4
