### ISSUE TITLE
Support of ES6 import

### ISSUE THREAD

**Issue by tleunen** [github-linker/chrome-extension#35]
Would be great to have a support of ES6 import syntax

**Comment by stefanbuck** [comment]
Definitely, PR welcome :wink:

**Comment by tleunen** [comment]
Will try to find some time to check this. Seems to be in core though.
I'll close this one because you already entered an issue about that here https://github.com/github-linker/core/issues/14

**Comment by stefanbuck** [comment]
Cool, take a look to this file https://github.com/github-linker/core/blob/master/lib/modules/require.js. It should be not hard to implement, hopefully :wink:
