### ISSUE TITLE
Permission confusion

### ISSUE THREAD

**Issue by camsong** [github-linker/chrome-extension#40]
![image](https://cloud.githubusercontent.com/assets/948896/9434117/c172b54a-4a6d-11e5-99dd-6ce0ee8bc78a.png)

How come it needs the `change` permission?

> Read and change your data on gist.github.com, github.com, and githublinker.herokuapp.com.

**Comment by stefanbuck** [comment]
No worries, it's just need for the communication with the live resolver API. For details, check out the release notes :wink: 
https://github.com/github-linker/chrome-extension/releases

**Comment by stefanbuck** [comment]
If there is something still unclear don't hassle to ask.

**Comment by camsong** [comment]
make sense, thanks.
