### ISSUE TITLE
Lazy/pre-load

### ISSUE THREAD

**Issue by barryvdh** [github-linker/chrome-extension#48]
Since the changes is loading it on request, using the API. we can't directly see the link anymore on hover.

Perhaps a few possibilities: 
- When the document has loaded, request all the packages
- Load the link on hover, instead of click.

Although the first option would dramatically increase the API requests. Could partially be overcome by using some local cache with recent items?

**Comment by stefanbuck** [comment]
Why are you interested in seeing the URL up front? Can you please share your concerns with me.

**Comment by barryvdh** [comment]
Not something specific, mostly just curious where it links to.

**Comment by stefanbuck** [comment]
Then just wait a sec :stuck_out_tongue_winking_eye: 

Prefetching all links on every page will be definitely overkill and to heavy for the API / my heroku plan. Even with a local cache, the server would be busy all the time.

**Comment by barryvdh** [comment]
But it only starts loading when clicked right, not hover? 
But fair enough, I'll see for now and otherwise look into a PR ;)

**Comment by stefanbuck** [comment]
Ahh sorry, I overread your hover idea. Yes that could work :wink:
