### ISSUE TITLE
Chrome extension memory usage

### ISSUE THREAD

**Issue by techniq** [github-linker/chrome-extension#50]
Currently the GitHub Link extension is the largest memory consumer under Chrome's task manager :(

![github-linker-memory](https://cloud.githubusercontent.com/assets/177476/9837207/97d93fa4-5a05-11e5-91c7-8e8e965b8cf4.png)

**Comment by stefanbuck** [comment]
Are you using the latest version `3.8.3`?

**Comment by techniq** [comment]
Yes, `3.8.3`

**Comment by stefanbuck** [comment]
After surfing a while on github.com my memory usage is still around ~48MB. I guess it's an edge case memory leak. Can you reproduce it easily? If so, please describe the steps that would be really helpful.

**Comment by techniq** [comment]
I visit a lot of github pages which might be causing it.  This morning it was at ~700MB.  I just disabled and reenabled the extension and will keep an eye on it.  I did a heap dump earlier to try to figure out what was taking up the memory but couldn't made out anything myself.

**Comment by stefanbuck** [comment]
@techniq is the memory usage still an issue for you?

**Comment by techniq** [comment]
@stefanbuck I haven't noticed it again (at least bad enough that would make me look for it).  My current uptime is only ~4 days, but I just checked, and the extension was at 34.8MB.  Closing issue.  Thanks
