### ISSUE TITLE
Packagist fallback for Composer

### ISSUE THREAD

**Issue by barryvdh** [github-linker/chrome-extension#52]
If the composer lookup fails, you could use the Packagist link instead: `https://packagist.org/packages/{vendor}/{client}`
eg. https://packagist.org/packages/google/apiclient

**Comment by stefanbuck** [comment]
Would you like to submit a PR for that? https://github.com/github-linker/live-resolver/blob/master/src/resolver/composer.js

**Comment by stefanbuck** [comment]
Implemented see https://github.com/github-linker/live-resolver/pull/4
