### ISSUE TITLE
Defer execution a tad

### ISSUE THREAD

**Issue by paulirish** [github-linker/chrome-extension#54]
Been noticing this slows down page loads lately...

![image](https://cloud.githubusercontent.com/assets/39191/10623816/513d7d12-7747-11e5-8213-7361ab408a41.png)

Here you can see Linker is definitely the most expensive of all my extensions.

Is there any reason it needs to run immediately at document_end ? I'd much prefer `document_idle`

it will run at window.load or 200ms after DOMContentLoaded, whichever comes first.

src: https://code.google.com/p/chromium/codesearch#chromium/src/extensions/renderer/script_injection_manager.cc&sq=package:chromium&type=cs&q=f:script_injection_manager%20%22We%20try%20to%20run%20idle%20in%20two%20places%22&l=141

It'd definitely give the browser a chance to do some work before handing over another 180ms of execution

**Comment by paulirish** [comment]
hooked up this SO answer to clarify this a bit: http://stackoverflow.com/q/33248629/89484

**Comment by stefanbuck** [comment]
Yeah, I should definitely change that. Thanks for the hint.
